import type {Metadata} from 'next'
import {Montserrat} from 'next/font/google'
import React from "react";
import Provider from "@/app/Provider";

const montserrat = Montserrat({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={montserrat.className}>
    <Provider>
      {children}
    </Provider>
    </body>
    </html>
  )
}
